name: fb-ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read
  packages: write # Permission needed to publish packages

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: node apps/server.js

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun

      - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - uses: nrwl/nx-set-shas@v4
      # - run: npx nx reset
      # Run lint, test, and build tasks for ng-flexbot library
      # - run: npx nx run ng-flexbot:lint
      - run: npx nx run ng-flexbot:test
      - run: npx nx run ng-flexbot:build

      # Publish ng-flexbot to npm
      - name: Publish ng-flexbot to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish dist/libs/ng-flexbot

      # Run end-to-end tests
      - run: npx nx run ng-flexbot:e2e